# In ubuntu 16.04 by default there is no python2
- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  tags:
    - common

- name: install curl, git, python-mysqld
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - git
    - python-mysqldb
  tags:
    - common